canal:
  mq:
    configuration:
      instance: canalMqExample
      filter: canal_client_example.t_user
      show-entry-log: true
      show-event-log: true
      enable-logic-delete: true
      logic-delete-field: deleted
    enabled: true
    consumer-config-map:
      canal_client_example:
        t_user:
          filter:
            aviatorExpression: phone == '1'